# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
      - id: forbid-secret-json
        name: Don't commit secret JSON files
        entry: Cannot commit secret JSON files
        language: fail
        files: 'secret.*\.json$'
      - id: forbid-credentials-yaml
        name: Don't commit credential YAML files
        entry: Cannot commit credential YAML files
        language: fail
        files: '.*credential.*\.yaml$'
